### ISSUE TITLE
System sends password on the wrong email

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#1]
Summary: When I try to restore pasword using "Forgot?" system shows message that it sends password. But I put invalid email.
Enviroment:  web
Steps to reproduce:
1. Open login page: https://staging-app.travelbank.com/
2. Click button "Forgot?".
3. Enter invalid email in "Email field". Like that: richard@gmail.com.
4. Click button"Submit".
 Actual Result: System shows message "A link to reset your password has been sent to your email". I didn't see letter in the catcher.
![wrong email](https://cloud.githubusercontent.com/assets/16305287/17732205/581c5e44-6479-11e6-9906-f7f35c284a6f.PNG)
Expected result: System have to show something like that: "User with this email doesn't exist"

**Comment by okryvorotko** [comment]
There is no such requirement. System behaves as the following:
1. You're typing email;
2. If it exists - email sent;
3. If not - not sent.
