### ISSUE TITLE
Updating returned expense report

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#100]
Summary: Updating returned expense report is with mistakes.
Env: IOS.
Steps:
1. Create local expense as traveler. Submit it.
2. Login as manager. Return it.
3. Login as traveler. Update it. Click button "Save".
Actual result: Extra buttons in the page. 
![actual](https://cloud.githubusercontent.com/assets/16305287/19077635/17290092-8a56-11e6-8cec-539140f51400.jpg)
Expected result: there is name of local expense in the top and thee is no button "Save".
![expected](https://cloud.githubusercontent.com/assets/16305287/19077705/521aa11a-8a56-11e6-9c1f-64b0d9b82391.jpg)

**Comment by okryvorotko** [comment]
Please provide more accurate steps to reproduce and expected result.

**Comment by karharadon** [comment]
First picture is actual result. Second expected. After last action we have buttons from another page.
