### ISSUE TITLE
Submitted expense report

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#108]
Traveler(taveler@tbtest.com/password) creates a trip. Manager(manager@tbtest.com/password) accepts it. Traveler adds expense and submits it. We have expense report wich can be approved or declined by manager:
![unnamed 16](https://cloud.githubusercontent.com/assets/16305287/19191203/0c9f23bc-8caa-11e6-9f7d-91ff7170f5a3.jpg)

Some questions about this report in current state:
1. There is no picture with local expense. But we have some standart background. Is it right?
2. Why we have float number? Is it wrong calculation or some commission?

After approving:
![unnamed 15](https://cloud.githubusercontent.com/assets/16305287/19191487/5751569a-8cab-11e6-9318-447422604092.jpg)

Questions:
3. There is no button "Mark as Paid". Is it right?
4. There is button "Add an Expense". (But if try to add, fill out and save it  we will have an error message). Is it good that we have possibility to add expense after approving?
5. Few days ago we can unapprove approved expence report. Now there are no button "...". Is it right?

**Comment by okryvorotko** [comment]
fix grammar mistakes

**Comment by karharadon** [comment]
6.. If we return this expense report we also will have button "Add an Expense". Look picture №2.
