### ISSUE TITLE
changing password

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#11]
Summary: system shows too difficult message when I change password (using not valid current password)
Enviroment: WEB
Steps to reproduce:
1. Login as traveler. 
2. Click "Profile" -> "Password".
3. In field "current password" put invalid password, in field "new password" any 8 characters.
4. Click "Submit".
![change password with wrong password](https://cloud.githubusercontent.com/assets/16305287/17733133/c7f0c940-647d-11e6-9611-d47f318b0086.PNG)
Actual result: System shows error message .
Expected result: System shows different price in front of enabled services.

**Comment by okryvorotko** [comment]
Cannot reproduce on Android and Web

**Comment by karharadon** [comment]
I can't  reproduce it too. Maybe they fixed it.
