### ISSUE TITLE
Declined trip

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#115]
Env: IOS
Steps to reproduce:
1. Login as traveler(t@tbtest.com/password).
2. Create trip. Submit it.
3. Login as manager(m@tbtest.com/password). Decline this trip.
4. Login as traveler. Click on the appropriate trip.
![unnamed](https://cloud.githubusercontent.com/assets/16305287/19292606/ffcde766-9025-11e6-9e29-b7f11d46b075.jpg)
Actual result: System shows message that trip will be approved by manager. But it is already returned. Traveler can't manipulate with trip.
Expected result: System allows traveler to do some actions with returned trip.

**Comment by okryvorotko** [comment]
Seems to be that m@tbtest.com is not a manager in this department
