### ISSUE TITLE
Bussines + Standart. First + Luxury. Options don't work.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#12]
Summary: when I as manager changed options "Airfare" and "Ground Transportation" nothing changes for traveler. System shows the same message about "econom class" during the different options.
Enviroment: WEB
Steps to reproduce:
1. Login as manager. 
2. Click "Profile" -> "Test Department" -> "Benchmark options" 
3. Activate "Luxury" and "First". Click "Save".
![options first luxury](https://cloud.githubusercontent.com/assets/16305287/17733265/74b56e1a-647e-11e6-913b-619bd264e1ba.PNG)
4. Logout.
5. Login as traveler.
6. Click "Trip".
7. Choose any cities and any dates. Click "Next".
8. Activate all services.
9. Click "Info" in every service window.
![airfare luxury result](https://cloud.githubusercontent.com/assets/16305287/17733660/6b6e6d96-6480-11e6-8d8f-5dbf80da15d0.PNG)
![transportation firs result](https://cloud.githubusercontent.com/assets/16305287/17733662/6b7d6ddc-6480-11e6-9b73-7da07b1f818e.PNG)
![hostel 5 stars](https://cloud.githubusercontent.com/assets/16305287/17733661/6b79da8c-6480-11e6-9269-113a5f015958.PNG)
![rail firs result](https://cloud.githubusercontent.com/assets/16305287/17733663/6b7ed6a4-6480-11e6-93da-d389c6bf9975.PNG)
Actual result: System shows messages with word "econom" or "lowest cost" + unexpected numbers.
Expected result: System shows messages with "luxury", "first" etc.
Sevirity: critical.

**Comment by karharadon** [comment]
Did you see numbers on the pictures? Do they mean that system used some numbers of the resources to create average price or is it bug? Because those extra number exist after repair.

**Comment by karharadon** [comment]
Retesting.
Benchmark options:
![options first luxury](https://cloud.githubusercontent.com/assets/16305287/17895074/88c5ae94-6954-11e6-9390-74083e99f908.PNG)
Result:
![railway](https://cloud.githubusercontent.com/assets/16305287/17895192/f329c4f0-6954-11e6-9ed7-b33ba5f692a2.PNG)

Railway options have issue.

**Comment by karharadon** [comment]
Nothing changed. Railway options have issue.
Benchmark options: luxury/first. Result:
![railway](https://cloud.githubusercontent.com/assets/16305287/18232335/5a08b480-72d6-11e6-865b-3adf9f9a7c5d.PNG)
![railway 2](https://cloud.githubusercontent.com/assets/16305287/18232336/5a10f7bc-72d6-11e6-9079-0285d502cae8.PNG)

**Comment by okryvorotko** [comment]
We must arrange call on it. I can't repro on IOS and WEB(chrome)
