### ISSUE TITLE
trip to the past

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#17]
Summary: There is a possibility to enter old date during trip creation.
Enviroment: web.
Steps to reproduce:
1. Login as traveler.
2. Click button "Trips".
3. Click "+".
4. Choose cities
5. Choose "Returning date". For example 01/01/2015.
6. Then choose "Departing date". For example 18/08/2016.
![srange trip main form](https://cloud.githubusercontent.com/assets/16305287/17737627/87f2525a-6496-11e6-9a63-05762e109931.PNG)
7. Click next.
8. Enable services.
![strange trip 1](https://cloud.githubusercontent.com/assets/16305287/17737658/a61fac6e-6496-11e6-9084-ad882c1d4e21.PNG)
![strange trip 2](https://cloud.githubusercontent.com/assets/16305287/17737664/a9b4a032-6496-11e6-976e-b514bd51c404.PNG)
Actual result: System allows to create trip to the past and to calculate this trip. 
Expected result: System doesn't allow to create trip with invalid date.

**Comment by karharadon** [comment]
This problem has fixed in current place. But I can choose invalid dates before trip submitting. For example:
![strang 2](https://cloud.githubusercontent.com/assets/16305287/17896604/eb5310e2-6959-11e6-9abf-2f6ccdd778e7.PNG)
![strange trip](https://cloud.githubusercontent.com/assets/16305287/17896603/eb4c2d9a-6959-11e6-9607-e92f0c70a47c.PNG)

**Comment by okryvorotko** [comment]
This is a different bug, not described in this issue. Create new one.

**Comment by karharadon** [comment]
![trip to the past](https://cloud.githubusercontent.com/assets/16305287/18782071/4781485c-818d-11e6-93f9-02a4afd2c73c.PNG)
still exist
and yes , I can click "Next" and work with this trip
on Android and WEB

**Comment by karharadon** [comment]
still exist
