### ISSUE TITLE
Different short names of the cities

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#18]
is it bug if city names are different?
![nyp - nyc](https://cloud.githubusercontent.com/assets/16305287/17742066/3b326aca-64a7-11e6-81f2-0e08bb02c6b0.PNG)
![city bug](https://cloud.githubusercontent.com/assets/16305287/17742229/d3f5626c-64a7-11e6-93e0-1bacd6778a1a.PNG)

is it different travel stations or maybe it is different towns, etc.

**Comment by okryvorotko** [comment]
No. This is only abbreviations which have a meaning known by developers.

**Comment by karharadon** [comment]
but users also will see this abreviations and thinking what is the strange town

**Comment by okryvorotko** [comment]
This is international codes of airports and rails

KBR - Kyiv Boryspil

**Comment by karharadon** [comment]
so, different organizations, ok
