### ISSUE TITLE
align trip information

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#19]
Summary: Data is unevenly located in process of trip creation.
Environment: web.
Step to reproduce:
1. Login as traveler.
2. Create trip.
3. Look into the data before submitting.
![not direct 2](https://cloud.githubusercontent.com/assets/16305287/17748730/6b401138-64c3-11e6-9d22-2f7b95a60b23.PNG)
![not direct](https://cloud.githubusercontent.com/assets/16305287/17748731/6b423f76-64c3-11e6-9751-c883969e7e32.PNG)
Actual result: The tables are crooked.
Expected result: the tables must lie symmetrically.

**Comment by okryvorotko** [comment]
What browser?

**Comment by karharadon** [comment]
Chrome. FireFox.

**Comment by karharadon** [comment]
There are no cities in block Daily Allowance. Maybe they are not needed if we calculate allowance in general, but allowance are devided on 3 row, so I suppose there shoud be cities in front of them.

![qqqqqq](https://cloud.githubusercontent.com/assets/16305287/18231875/588c3fdc-72cc-11e6-9762-af5ce951c55d.PNG)
