### ISSUE TITLE
Manager can't approve traveler expence report.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#20]
Summary: Manager can't approve traveler expence report.
Environment: web.
Steps to reproduce:
1. Login as traveler. Create trip with any information. Sumbit. Logout.
2. Login as manager. Accept this trip. Logout.
3. Login as taveler.  Click "Trips" -> click trip you have created - >click "+"(to add new expense)
4. full all fields, add photo. save.
5. Click "..." -> "Submit expense report" -> "ok". Logout.
6. Login as manager.  Click "Expense reports" -> choose your trip -> "Approve".
System shows message but stay in the same page.
![not approved](https://cloud.githubusercontent.com/assets/16305287/17777067/c229ddc2-6567-11e6-9e84-2566d1948913.PNG)
7. Click "Approve" again.
Actual result: System throws user from the system on a login page.
Expexted result: System approve expense report and show another page in the system.

**Comment by okryvorotko** [comment]
Cannot execute 7 step because i have only one button - Mark as Paid.
Cannot approve twice.

**Comment by karharadon** [comment]
it is gone!
