### ISSUE TITLE
TC №C23

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#24]
![8](https://cloud.githubusercontent.com/assets/16305287/17858324/e136dd9a-688d-11e6-8a0a-a7041565496f.PNG)
![9](https://cloud.githubusercontent.com/assets/16305287/17858323/e1314e0c-688d-11e6-9276-75aa1f7896f0.PNG)

**Comment by okryvorotko** [comment]
This is a bug. Cancelling will be returned back.

**Comment by karharadon** [comment]
ok! although, it was another singn in front of the trip before today. and I think it is not "minor" but "major". Who have deleted label "normal"?

**Comment by okryvorotko** [comment]
I don't understand your question. Please rephrase.

**Comment by karharadon** [comment]
Let's try again. Question was: There are no possibility to cancel (delete) declined trip. Because:
1.  Manager opens submited trip. He must click on a trip (there are no another way to do something with the trip). And he sees:
   ![23-2](https://cloud.githubusercontent.com/assets/16305287/17897257/3490c536-695c-11e6-8857-2e9b9f074fa2.PNG)
2. So he clicks " Decline". And he sees:
   ![23-1](https://cloud.githubusercontent.com/assets/16305287/17897305/5d1ca164-695c-11e6-94ca-5bb1c844e0a1.PNG)
3. So he shoud choose this trip again that he can do something with it. He click ans sees:
   ![23](https://cloud.githubusercontent.com/assets/16305287/17897338/7f88dc68-695c-11e6-9152-79099ee7c8b5.PNG)

So there are no possibility to cancel (delete) declined trip.
Or you can Accept the trip and only after that you can Cancel it.

I dont know how  you have could cancel the trip that it has been returned to the traveler:
![1](https://cloud.githubusercontent.com/assets/16305287/17906482/359251a6-6980-11e6-91d6-46abd5c56e19.PNG)

**Comment by okryvorotko** [comment]
Traveler can cancel declined trip. Manager can't.
