### ISSUE TITLE
Not full data in the mail

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#25]
I have requested the data.

![11](https://cloud.githubusercontent.com/assets/16305287/17860962/e48136e4-6897-11e6-9016-5024c558b6ad.PNG)
![10](https://cloud.githubusercontent.com/assets/16305287/17860961/e47a2f98-6897-11e6-8a02-71ea58ce3914.PNG)

But I have received only title without any real information in the letter.  Hasn't this functionality accomplished?

**Comment by okryvorotko** [comment]
Mail and male - different things))

**Comment by karharadon** [comment]
Question is not closed!)

**Comment by okryvorotko** [comment]
Closed

**Comment by okryvorotko** [comment]
There is a attachment in mail. Check it.
