### ISSUE TITLE
Category disappears in Local Expense.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#29]
Summary: Category desappears after saving Local Expense.
Environment: web.
Steps to reproduse:
1. Login as traveler.
2. Create local expense. Save it.
3. Open the same expense.
![11111111111111](https://cloud.githubusercontent.com/assets/16305287/17967262/c479c616-6ace-11e6-8e9c-9cdf73127889.PNG)
Actual result: Dropdown list doesn't show category that you have been choosed before, it is empty.
Expected result: Category is saved.

**Comment by karharadon** [comment]
Summary: Category desapears after saving Local Expense.
Environment: web.
Steps to reproduse:
1. Login as traveler.
2. Create local expense. Save it.
3. Open the same expense.
![11111111111111](https://cloud.githubusercontent.com/assets/16305287/17967262/c479c616-6ace-11e6-8e9c-9cdf73127889.PNG)
Actual result: Dropdown list doesn't show category that you have been choosed before, it is empty.
Expected result: Category is saved.

**Comment by okryvorotko** [comment]
I would say that it is critical bug. It has no influence on the process, but manager can be really confused while looking through expenses.
