### ISSUE TITLE
Category management. Wrong toogles functionality.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#30]
Summary: Toggles in Category Managment behave irrationally.
Environment: web.
Steps to reproduce:
1. Login as manager.
2. Click "Profile" -> "Test Department" -> "Category Managment" -> "Enabled".
![default](https://cloud.githubusercontent.com/assets/16305287/17971877/4aa11b34-6ae5-11e6-9828-a1e8f51f73fd.PNG)
3. Enter into few enabled Categories. 
![toggle 4](https://cloud.githubusercontent.com/assets/16305287/17972045/0d7b30c2-6ae6-11e6-90cc-7fba00d86314.PNG)
![toggle](https://cloud.githubusercontent.com/assets/16305287/17972046/0d801fe2-6ae6-11e6-9383-12f5ed58cb14.PNG)
![toggle 2](https://cloud.githubusercontent.com/assets/16305287/17972047/0d7ff1ac-6ae6-11e6-8cbe-da4dc01fd4ef.PNG)
![toggle 3](https://cloud.githubusercontent.com/assets/16305287/17972048/0d85c83e-6ae6-11e6-9a3b-f2524a4cad43.PNG)
Actual result: some of toogles are disabled.
Expected result: all toogles in section "Enabled" must be enabled.
4. Try to move few Categories from "Enabled" to "Disabled" and back.
Actual result: Sometimes you shoud click twice on toogle that it moves to another section. 
Expected result: Manager should click toogle once to move Category from one section to another.

**Comment by karharadon** [comment]
Nothing changed. All the same.

**Comment by okryvorotko** [comment]
Can't repro. We need to arrange call on that

**Comment by okryvorotko** [comment]
Bug #622
