### ISSUE TITLE
Updating submitted trip: Permissions

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#31]
There are TC:
https://travelbank.testrail.net/index.php?/tests/view/780&group_by=tests:original_case_id&group_order=asc&group_id=-1

We have string there: Traveler/Manager(owner/ not owner).

No one can update submited multiple trip. 

So should I delete TC or it is bug in functionality or I don't understand  TC name.

Can you tell me what does it mean "permissions" here?

**Comment by okryvorotko** [comment]
It means that you should check that nobody can't update submitted trip.
This is what called permissions - if one can update or not. Allowed or not. If not - this is also requirement. This should be checked. Because update of submitted trip can cause bad consequences.

**Comment by karharadon** [comment]
Nobody can! So is it good and I ll close issue?

**Comment by okryvorotko** [comment]
You should check that edition is not allowed.
You may close the issue.
