### ISSUE TITLE
Names are not shortened.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#35]
I know it is very little bug:) So should I create it?)
![5](https://cloud.githubusercontent.com/assets/16305287/18010800/be26d834-6bba-11e6-87fc-958030ba4c53.PNG)

**Comment by okryvorotko** [comment]
Yes. To let them know that it is possible.

**Comment by karharadon** [comment]
Summary: Name are not shortcut.
Environment: web.
Precondition: Traveler with a very long name.
Steps to reproduce:
1. Login as traveler.
2. Create trip with any data.
3. Submit this trip.
![5](https://cloud.githubusercontent.com/assets/16305287/18010800/be26d834-6bba-11e6-87fc-958030ba4c53.PNG)
Actual result: The name overlaps a price.
Expected result: There are some space between name and price.

**Comment by okryvorotko** [comment]
![screen shot 2016-09-02 at 4 10 56 pm](https://cloud.githubusercontent.com/assets/15108766/18204890/e259bbc8-7127-11e6-8b0f-f8c306bcce97.png)

**Comment by karharadon** [comment]
![shortcut](https://cloud.githubusercontent.com/assets/16305287/18231510/0e5d8c8e-72c4-11e6-8120-07e4105b763d.PNG)

**Comment by okryvorotko** [comment]
They don't say like this. You'd better say - names are shortened.

**Comment by karharadon** [comment]
changed

**Comment by karharadon** [comment]
![unnamed 1](https://cloud.githubusercontent.com/assets/16305287/18988064/9371cc2a-870d-11e6-931a-c711e15064c3.jpg)
Can't say that it is looks like nice... but bug 701 is closed.
