### ISSUE TITLE
TC C84

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#37]
I don't see functionality to unsubmit expense report:

https://travelbank.testrail.net/index.php?/tests/view/830&group_by=tests:original_case_id&group_order=asc&group_id=-1

**Comment by okryvorotko** [comment]
Manager can Unapprove report when it is approved and not paid. Look for three dots in right upper corner

**Comment by karharadon** [comment]
if manager do that we will have returned expense report. And we already have "Returned expense report".
![9](https://cloud.githubusercontent.com/assets/16305287/18054632/5362111c-6e0d-11e6-8e61-e9af23369eb6.PNG)

**Comment by okryvorotko** [comment]
Rename TC to `Unapprove expense report` and delete duplicate

**Comment by karharadon** [comment]
I have renamed TC to "Unapprove expense report". But have delete nothing. Will speak about this later.
