### ISSUE TITLE
TC C87: Adjust TCs

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#39]
I dont understand how to create this case:
https://travelbank.testrail.net/index.php?/tests/view/833
maybe this letter have to come after click "Mark as Paid"?

**Comment by okryvorotko** [comment]
You can rename it to Mark as Paid.

**Comment by karharadon** [comment]
or after Approving Expence report and before Mark as Paid?

When this message will be actual? Or can you ask them? Because I haven't seen letter with this massage yet.
"Manager does. Traveler receives
Hooray! You Got Paid"

**Comment by okryvorotko** [comment]
Email supposed to appear after Mark as Paid clicking.
Create bug for it

**Comment by karharadon** [comment]
Functionality has been changed: they have deleted "Mark as Paid" after "Approve/Discard". Also there are not function "Unapprove". If I approve exp rep it will be final step an system will mark exp rep as paid by sign (green $). Also I have received a letter with such message:
![last email](https://cloud.githubusercontent.com/assets/16305287/18232209/7e803c5a-72d3-11e6-812f-70376262d39a.PNG)

I propose:
1. change text of the message in current TC.
2. don't create bug - letter is!
3. delete next TC, because we havent posibility unapprove Approwed Trip:
![unaprove exp rep](https://cloud.githubusercontent.com/assets/16305287/18232224/d8eb29f2-72d3-11e6-82f2-db58c3b6c9c3.PNG)

**Comment by okryvorotko** [comment]
Agree

**Comment by karharadon** [comment]
done!
