### ISSUE TITLE
TC C96 / 842 (Approve Expense Report from Local Expenses)

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#40]
https://travelbank.testrail.net/index.php?/tests/view/842&group_by=cases:section_id&group_id=9&group_order=asc
![8](https://cloud.githubusercontent.com/assets/16305287/18053887/3ea0ffb6-6e0a-11e6-82d1-7e9e9afed720.PNG)

Wich user? I guess manager?

Approve Expense Report from Local Expenses ? How to do that? Maybe from Expense Report?

**Comment by okryvorotko** [comment]
Rename to "Submit expense report..." 

When you create local expense you get redirected into trip. From there you have a possibility to Submit expense report.
