### ISSUE TITLE
TC C97 / 843 (Discard Expense Report from Local Expenses)

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#41]
https://travelbank.testrail.net/index.php?/cases/view/97

Wich user? I guess manager?

Approve Expense Report from Local Expenses ? How to do that? Maybe from Expense Report?

**Comment by okryvorotko** [comment]
I don't remember. Maybe this functionality was present before. Now i can't find it neither.

**Comment by karharadon** [comment]
so? should I delete this TC?

**Comment by okryvorotko** [comment]
Yes. Delete
