### ISSUE TITLE
Align buttons, firefox

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#42]
1. Align buttons.
2. Can't attach photo to loc exp.

**Comment by okryvorotko** [comment]
please, describe first issue with screenshots

**Comment by karharadon** [comment]
I have created this issue for me, for future, because you had said that FireFox don't touch. But if you want:
Enter in every main section and look into signs:
![lllllllllllllll](https://cloud.githubusercontent.com/assets/16305287/18231566/5c46522c-72c5-11e6-836b-2f4f934a328c.PNG)
![xxxxxxxxxxx](https://cloud.githubusercontent.com/assets/16305287/18231568/5c66f4b4-72c5-11e6-849d-c5bf94b3b901.PNG)
![zzzzzzzzzzzzz](https://cloud.githubusercontent.com/assets/16305287/18231569/5c7dcffe-72c5-11e6-8656-b3bd39f68abf.PNG)
![ccccccc](https://cloud.githubusercontent.com/assets/16305287/18231570/5c83e4e8-72c5-11e6-9a48-b131b250ea1c.PNG)

**Comment by okryvorotko** [comment]
Bug #739
