### ISSUE TITLE
Unstable airfare calculations before trip subitting.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#45]
Summary: When I create trip, enable airfare and refresh this block every  few seconds, system shows me different prices. 
Environment: web
Steps to reproduse:
1. Login as any user.
2. Start to create trip with ane cities and dates.
3. Click next.
4. Enable block "Airfare".
5. Click button "Refresh" few times.
6. Compare prices.
Actual result: Prices are very different.
Expected result: Prices are similar.

**Comment by okryvorotko** [comment]
Can't repro. We need to arrange call.
