### ISSUE TITLE
Float numbers in the trip.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#47]
Summary: When I create trip, enable lodging, updating dates, system shows me wrong calculations. 
Environment: web
Steps to reproduse:
1. Login as any user.
2. Start to create trip with ane cities and dates.
3. Click next.
4. Enable all blocks.
![cents](https://cloud.githubusercontent.com/assets/16305287/18181160/91b30822-7092-11e6-8348-47dd2fa6d797.PNG)
![jutyrhgfe](https://cloud.githubusercontent.com/assets/16305287/18181663/e7ae5900-7094-11e6-8f85-2420d81a6524.PNG)
Actual result: Total block prices are float numbers. But avg/day(night, flight...) are integer.
Expected result: all numbers are integer.

**Comment by okryvorotko** [comment]
This is not a bug. This is a question. Because we don't know how should it be.

**Comment by karharadon** [comment]
![image](https://cloud.githubusercontent.com/assets/16305287/18757326/1e9c0472-80fc-11e6-9b44-f6eabf4aea14.png)

![default](https://cloud.githubusercontent.com/assets/16305287/18757339/2f1dac7e-80fc-11e6-99d4-52e917c3b16a.PNG)

Return it.

**Comment by karharadon** [comment]
they have fixed in this place, but I have found in new. So I close this question. And will open new bug.
