### ISSUE TITLE
Test department. Buttons hide.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#50]
Summary: Buttons and one profile are partly hidden in Test Department.
Env: web.
Steps to repro:
1. login as manager.
2. Go to "Profile" -> "Test Department".
![ppppppppppppppppppppppppppppp](https://cloud.githubusercontent.com/assets/16305287/18232459/cc12b9b6-72d8-11e6-90cc-ce2c0146cbe2.PNG)

**Comment by okryvorotko** [comment]
UI bug on Web only. Does not appear on IOS and Web. Priority: minor

**Comment by karharadon** [comment]
ok, are you going to take it in progress?
