### ISSUE TITLE
Railway. Only economy itineraries.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#52]
We have talked about that. There are no possibility to change benchmark options for railway. Or railway relates to ground transportation and we have bug:)

**Comment by okryvorotko** [comment]
![screen shot 2016-09-06 at 3 10 30 pm](https://cloud.githubusercontent.com/assets/15108766/18273060/1910c4c6-7444-11e6-811f-630a6a8adf70.png)

**Comment by karharadon** [comment]
so? what we do?

**Comment by okryvorotko** [comment]
Waiting for the real answer

**Comment by okryvorotko** [comment]
The answer is: fine for now.
