### ISSUE TITLE
Can't create trip. Names are not shortened.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#61]
Summary: Name overlaps a checkbox.
Environment: Android.
Preconditions: user with a long name.
Steps to reproduce:
1. Login as manger.
2. Start trip ceating for user with a long name.
![ksmdefhohgm](https://cloud.githubusercontent.com/assets/16305287/18699790/1351c442-7fdc-11e6-9639-fd40ff06e94f.jpg)
Actual result: Can't choose user with the long name. Because the name overlaps the check box.
Actual result: There is possibility to tick in checkbox.

**Comment by okryvorotko** [comment]
duplicate of #35
