### ISSUE TITLE
Strange text on the Login page.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#63]
What does it mean this text? Is it bug? It is on Android and Web.
![tzf3qwrcnrw](https://cloud.githubusercontent.com/assets/16305287/18702671/62b7551a-7feb-11e6-977b-235e45d8c6d8.jpg)

**Comment by okryvorotko** [comment]
I suppose it should be deleted or replaced soon. I will mention this in our chat. Wont create bug

**Comment by karharadon** [comment]
ok, I will wait)

**Comment by okryvorotko** [comment]
<img width="532" alt="screen shot 2016-09-23 at 12 29 37 pm" src="https://cloud.githubusercontent.com/assets/15108766/18781203/7833a9ee-8189-11e6-8180-34bf8b02b79e.png">
