### ISSUE TITLE
Can't create local expense 2. There is no button "+".

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#70]
Summary: There is no button "+" in accepted trip. So traveler can't create local expense from the trip. 
Env: IOS.
Steps to reproduce:
1. Create trip as traveler. 
2. Accept as manager. 
3. Login as traveler.
4. Click "Trips" -> chose this trip.
<img width="459" alt="screen shot 2016-09-26 at 4 13 31 pm" src="https://cloud.githubusercontent.com/assets/16305287/18835685/0cb203cc-8405-11e6-9662-e7372664520a.png">
Actual result: there is no button "+".
Expected result: There is button "+".

**Comment by okryvorotko** [comment]
#1080
Button "+" in Trips gone
