### ISSUE TITLE
Local expense without expense

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#72]
There is possibility to create local expense which costs $0.00. Is it normal? It is a little bit strange logically.
<img width="487" alt="screen shot 2016-09-26 at 5 34 34 pm" src="https://cloud.githubusercontent.com/assets/16305287/18838447/2fff0e82-8410-11e6-9ae1-94d0b731303d.png">

**Comment by okryvorotko** [comment]
#1083
Can create expense with zero price
