### ISSUE TITLE
Travelator. Can't leave a page.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#75]
Summary: there is no button to leave page or to return back.
Env: IOS.
Steps to reproduce:
1. Login as traveler.
2. Go to "Terms of Use".
3. Click link "TRAVELBANK.COM".
<img width="487" alt="screen shot 2016-09-27 at 2 37 22 pm" src="https://cloud.githubusercontent.com/assets/16305287/18871835/ea4fb03e-84bf-11e6-8d32-e3ea575e2f79.png">
Actual result: Can't leave this page.
Expected result: there is possibility to go ahead or return back.

**Comment by okryvorotko** [comment]
#1147
Cannot leave Travelator page
