### ISSUE TITLE
Travelator. Food. Per Diem.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#76]
Summary: Small error message when food is activated.
Environment: IOS
Steps to reproduce:
1.Login as traveler.
2. Go to "Terms of Use".
3. Click on link "TRAVELBANK.COM".
4. Fill all fields. 
5. Activate service "Food".
6. Click button "Calculate".
<img width="487" alt="screen shot 2016-09-27 at 3 13 35 pm" src="https://cloud.githubusercontent.com/assets/16305287/18872826/0bbbacf0-84c5-11e6-85e2-6358e7597adf.png">
Actual result: System shows message: "PerDiem: [object Object]
Expected result: There are not unclear messages for user.

**Comment by okryvorotko** [comment]
#1148
Travelator: Food. Per Diem

**Comment by karharadon** [comment]
they have written that bug was closed. but there are no links to this functionality now. so I can't check.

**Comment by okryvorotko** [comment]
Obviously it was the fix
