### ISSUE TITLE
Traveler can't easy find his old trips

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#8]
Summary: Trip preview in traveler profile are without trip name, author avatar and author name.
Enviroment: WEB
Steps to reproduce:
1. Open login page: https://staging-app.travelbank.com/
2. Login with traveler.
3. Click "Trips".
![old trips](https://cloud.githubusercontent.com/assets/16305287/17731881/048e0a26-6478-11e6-8b15-ce697d5a85d9.PNG)
Actual result: System shows OLD trips without trip name, author avatar and author name.
Expected result: System shows ALL trips with avatar, author name and trip name.

**Comment by karharadon** [comment]
The situation became better. Trips names have been appeared. But there are not authors name in some trips which was created during the script migration. So I will close this bug, but I want you know about this little moment.

![15](https://cloud.githubusercontent.com/assets/16305287/17892414/d609936a-6949-11e6-92f4-676a7adf9570.PNG)

**Comment by okryvorotko** [comment]
I don't mind.
