### ISSUE TITLE
Parking. City code.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#84]
Summary: There no city code in additional information.
Env: IOS.
Steps to reproduce:
1. Login as traveler.
2. Start to create trip. Chose any cities and dates. Click "Next".
3. Enable block Parking.
4. Click button "Info".
<img width="487" alt="screen shot 2016-09-28 at 5 19 10 pm" src="https://cloud.githubusercontent.com/assets/16305287/18950323/fa384914-8647-11e6-9bf8-fd60750ce725.png">
Actual result: there are no city code after ":".
Expected result: After ":" should be city code.

**Comment by okryvorotko** [comment]
#1187
Parking. City code missing in info

**Comment by karharadon** [comment]
closed
