### ISSUE TITLE
Local Expense. Excess category "Select category".

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#88]
Summary: Category "Other" is default category in Local expense. So category "Select category" looks like excess.
Env: IOS.
Steps to reproduce:
1. Login as traveler.
2. Create local expense from Local expenses.
<img width="487" alt="screen shot 2016-09-29 at 5 33 10 pm" src="https://cloud.githubusercontent.com/assets/16305287/18958304/db9507b8-866a-11e6-822f-faf41be33711.png">

**Comment by okryvorotko** [comment]
#1190
Local Expense. Redindant category "Select category"
