### ISSUE TITLE
Sign up. Error message is hidden.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#92]
Summary: Can't see error message during  registration for new user.
Env:IOS
Steps to reproduce:
1. Go to Sign up page.
2. Enter email and VIP code. Submit.
3. Check email. Take activation code.
4. Click button "Have an activation code".
5. Fill all fields. Don't tick the checkbox "I agree ...".
6. Click button "Finish".
![unnamed 3](https://cloud.githubusercontent.com/assets/16305287/18989202/47996d20-8713-11e6-8dc4-5bb08e11fffc.jpg)
Actual result: Error message is hidden.
Expected result: Can see error message.

**Comment by okryvorotko** [comment]
#1037
Sign Up error overlap

**Comment by karharadon** [comment]
I can see error message in some cases. If keyboard is twisted and I tick checkbox after filling fields(something like that). But in most cases issue still exist.
![unnamed](https://cloud.githubusercontent.com/assets/16305287/19040952/ead4162a-898e-11e6-8ff7-67ea32430093.jpg)

**Comment by karharadon** [comment]
close it
