### ISSUE TITLE
San Francisco. Railway.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#93]
Summary: System shows error message when we create trip to San Francisco and enable service "Railway".
Env:IOS.
![unnamed](https://cloud.githubusercontent.com/assets/16305287/18989858/05410240-8717-11e6-85b8-9d986d0201c4.jpg)
![unnamed 1](https://cloud.githubusercontent.com/assets/16305287/18989859/0542684c-8717-11e6-966f-dd82d0462c39.jpg)

**Comment by okryvorotko** [comment]
What is other towns? Any town?

**Comment by karharadon** [comment]
read title please

**Comment by karharadon** [comment]
no, I have find only SF. Maybe there is no railway connection with SF, but anyway error message is not understandable for user
