### ISSUE TITLE
Local expense. Big numbers.

### ISSUE THREAD

**Issue by karharadon** [forFriends/travel#95]
Summary: if use big numbers ( more than six) program will throw you away from itself. Or will show error message.
Env: IOS.
Steps to repoduce:
1. Create new trip as traveler.
2. Submit it as manager.
3. Login as traveler.
4. Strart to create local expense following next steps:
   a) assign it to the trip
   b) chose "Category"
   c) fill out "Merchant" text field
   d) put 9 digits in "Total" field (I have used 999999999 or 111111111)
![unnamed 2](https://cloud.githubusercontent.com/assets/16305287/19071346/43194d42-8a38-11e6-998b-80acbb5ee742.jpg)
Acual result: program throws you away from itself.
Expected result: you can click button "Save" and bound expense report to the trip.
If you use 7 or 8 digits you pehaps will save this expens but will see eror message:
![unnamed 1](https://cloud.githubusercontent.com/assets/16305287/19071333/32ba3326-8a38-11e6-9732-66955de76d2f.jpg)

**Comment by okryvorotko** [comment]
Severity defined incorrectly. This bug can't be major.
